version: "3.8"
services: 
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    container_name: main-service
    ports: 
      - 8002:5000
    volumes: 
      - .:/app
    depends_on: 
      - db  
    networks:
      - microservice
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    container_name: main-queue
    depends_on:
      - db
    networks:
      - microservice
  db:
    image: mysql:5.7.22
    container_name: main-db
    restart: always
    environment: 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes: 
      - .dbdata:/var/lib/mysql
    ports:
      - 3308:3306
    networks:
      - microservice

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: main-pma
    links:
      - db:db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    restart: always
    ports:
      - 8003:80
    networks:
      - microservice



networks:
  microservice:
    driver: bridge


